#!/bin/bash

if [ $# = 0 ]; then
	echo "Usage: ./mkdev DST_DIR"
	exit
fi

INSTALL_ROOT=$1

mkdir $INSTALL_ROOT/dev/pts	
mknod $INSTALL_ROOT/dev/ar7100_flash_chrdev		c	239  	0	
mknod $INSTALL_ROOT/dev/ar7100_gpio_chrdev		c	238  	0	
mknod $INSTALL_ROOT/dev/caldata		b	31  	4
mknod $INSTALL_ROOT/dev/console		c	5  	1		
mknod $INSTALL_ROOT/dev/dk0			c	63 	0
mknod $INSTALL_ROOT/dev/kmem		c	1  	2		
mknod $INSTALL_ROOT/dev/mem			c	1  	1		
mknod $INSTALL_ROOT/dev/mtd0		c	90 	0
mknod $INSTALL_ROOT/dev/mtdblock0		b	31  	0
mknod $INSTALL_ROOT/dev/mtdblock1		b	31  	1
mknod $INSTALL_ROOT/dev/mtdblock2		b	31  	2
mknod $INSTALL_ROOT/dev/mtdblock3		b	31  	3
mknod $INSTALL_ROOT/dev/mtdblock4		b	31  	4
mknod $INSTALL_ROOT/dev/mtdblock5		b	31  	5
mknod $INSTALL_ROOT/dev/mtdblock6		b	31  	6
mknod $INSTALL_ROOT/dev/mtdr0		c	90  1
mknod $INSTALL_ROOT/dev/null		c	1  	3	
mknod $INSTALL_ROOT/dev/ppp			c	108	0	
mknod $INSTALL_ROOT/dev/ptmx		c	5	2
mknod $INSTALL_ROOT/dev/ptyp0		c	2	0
mknod $INSTALL_ROOT/dev/ptyp1		c	2	1
mknod $INSTALL_ROOT/dev/ptyp2		c	2	2
mknod $INSTALL_ROOT/dev/ram0		b	1	0	
mknod $INSTALL_ROOT/dev/random		c	1  	8		
mknod $INSTALL_ROOT/dev/tty			c	5  	0		
mknod $INSTALL_ROOT/dev/tty0		c	4	0
mknod $INSTALL_ROOT/dev/tty1		c	4	1
mknod $INSTALL_ROOT/dev/tty2		c	4	2
mknod $INSTALL_ROOT/dev/ttyS0		c	4	64
mknod $INSTALL_ROOT/dev/ttyS1		c	4	65
mknod $INSTALL_ROOT/dev/ttyS2		c	4	66
mknod $INSTALL_ROOT/dev/ttyp0		c	3	0
mknod $INSTALL_ROOT/dev/urandom		c	1  	9
mknod $INSTALL_ROOT/dev/zero		c	1	5	
mknod $INSTALL_ROOT/dev/ttyp1		c	3	1
mknod $INSTALL_ROOT/dev/ttyp2		c	3	2
