#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "mips-linux-uclibc-gcc -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DB_ENDIAN -DTERMIO -O3 -fomit-frame-pointer -Wall "
  #define PLATFORM "linux-elf"
  #define DATE "Tue Dec 16 17:50:11 CST 2008"
#endif
