#
# Makefile for advanced NAT
#
obj-$(CONFIG_NF_CONNTRACK_RTSP) += nf_conntrack_rtsp.o
obj-$(CONFIG_NF_NAT_RTSP) += nf_nat_rtsp.o

#obj-$(CONFIG_IP_NF_MATCH_CLASSIFY) += ipt_classify.o
obj-$(CONFIG_NETFILTER_XT_MATCH_WEBSTR) += xt_webstr.o
obj-$(CONFIG_NETFILTER_XT_TARGET_IMQ) += xt_IMQ.o
obj-$(CONFIG_IP_NF_TARGET_NATTYPE) += ipt_NATTYPE.o
